Repository unb-mds/2024-1-squad04, pull requests merged in 2024-06, with the labels that each got.

#49 40 filtragem de professores por matérias Front End
  vue-app/package-lock.json
  vue-app/src/assets/icons/pagina_professor/filter.svg
  vue-app/src/components/Navegacao/BarraDePesquisaComponent.vue
  vue-app/src/components/Navegacao/FiltroProfessoresPorMateriaComponent.vue
  vue-app/src/pages/LandingPage.vue
  vue-app/src/pages/ProfessorPage.vue
Labels: Improvement

#53 Nova pagina avaliacoes
  vue-app/src/assets/icons/avaliacao/like.svg
  vue-app/src/assets/icons/avaliacao/trash.svg
  vue-app/src/components/Avaliacao/CardMinhaAvaliacao.vue
  vue-app/src/components/Navegacao/NavBar.vue
  vue-app/src/pages/AvaliacaoPage.vue
  vue-app/src/pages/MateriasPage.vue
  vue-app/src/pages/ProfessorPage.vue
  vue-app/src/routes/index.js
Labels: enhancement

#57 fix(frontend): arruma o flip do card de professores na listagem
  vue-app/src/components/Navegacao/FiltroProfessoresPorMateriaComponent.vue
  vue-app/src/components/Professores/CardListagemProfessoresComponent.vue
  vue-app/src/components/Professores/PopupAvaliaProfessor.vue
  vue-app/src/components/Professores/RatingStarsProfessor.vue
  vue-app/src/service/professor/ManipulaDadosProfessorCardListagem.js
Labels: fix, High priority

#58 feat(minhas_avaliacoes): permite listagem e exclusão de avaliações de professores e matérias
  node-app/controllers/AvaliacaoMET.js
  node-app/controllers/UserMET.js
  node-app/index.js
  vue-app/src/components/Avaliacao/CardMinhaAvaliacao.vue
  vue-app/src/components/Avaliacao/CardMinhaAvaliacaoProfessor.vue
  vue-app/src/pages/AvaliacaoPage.vue
  vue-app/src/repositories/avaliacao/deletarAvaliacoes.js
  vue-app/src/repositories/usuario/obterAvaliacoesUsuario.js
  vue-app/src/service/avaliacao/deletarAvaliacao.js
  vue-app/src/service/usuario/getMInhasAvaliacoes.js
Labels: feature, API Integration, Medium priority

#67 feat: implementa página de usuário
  node-app/controllers/UserMET.js
  node-app/index.js
  vue-app/src/assets/icons/navegacao/back_arrow.svg
  vue-app/src/assets/icons/perfil/log-out-icon.svg
  vue-app/src/components/Navegacao/NavBar.vue
  vue-app/src/components/Usuario/PopUpEdicaoPerfil.vue
  vue-app/src/guards/authGuard.js
  vue-app/src/pages/LoginPage.vue
  vue-app/src/pages/PerfilPage.vue
  vue-app/src/repositories/usuario/obterInformacoesPerfilUsuario.js
  vue-app/src/routes/index.js
  vue-app/src/service/usuario/editarDadosPerfil.js
  vue-app/src/service/usuario/getInfoUserProfile.js
Labels: feature, API Integration, Medium priority

#73 feat: implementado filtragem das avaliações do professor de acordo com a materia selecionada
  node-app/controllers/ProfessorMET.js
  vue-app/src/components/Navegacao/FiltroProfessoresPorMateriaComponent.vue
  vue-app/src/components/Professores/InfoProfessorComponent.vue
  vue-app/src/components/Professores/PopupAvaliaProfessor.vue
  vue-app/src/pages/AvaliacaoPage.vue
  vue-app/src/pages/PerfilPage.vue
  vue-app/src/pages/ProfessorIndividualPage.vue
  vue-app/src/pages/ProfessorPage.vue
  vue-app/src/repositories/professor/obterProfessor.js
Labels: feature, API Integration, Medium priority

#77 fix: conserta flip cards de matéria
  vue-app/src/components/Materias/CardListagemMateriasComponent.vue
  vue-app/src/components/Professores/CardListagemProfessoresComponent.vue
  vue-app/src/pages/MateriasPage.vue
Labels: fix, Low priority

#79 feat: deixa a página individual de professores responsiva
  vue-app/src/components/Professores/InfoProfessorComponent.vue
  vue-app/src/pages/ProfessorIndividualPage.vue
Labels: feature

#80 feat: permite curtir e descurtir avaliações de professores
  node-app/controllers/ComentarioMET.js
  node-app/controllers/MateriaMET.js
  node-app/controllers/ProfessorMET.js
  node-app/controllers/UserMET.js
  node-app/index.js
  vue-app/src/components/Professores/InfoProfessorComponent.vue
  vue-app/src/generals/descriptografarDados.js
  vue-app/src/generals/encripitarDados.js
  vue-app/src/guards/authGuard.js
  vue-app/src/pages/LoginPage.vue
  vue-app/src/pages/PerfilPage.vue
  vue-app/src/repositories/comentario/deletarLikeDislikeProfessor.js
  vue-app/src/repositories/comentario/editarRelacionamentoUsuarioComentario.js
  vue-app/src/repositories/comentario/enviarLikeDislikeProfessor.js
  vue-app/src/repositories/usuario/obterUsuarios.js
  vue-app/src/routes/index.js
  vue-app/src/service/comentario/comentarioProfessor.js
  vue-app/src/service/comentario/descurtirComentarioProfessor.js
  vue-app/src/service/usuario/getInfoUserProfile.js
  vue-app/src/service/usuario/getMInhasAvaliacoes.js
Labels: feature, API Integration, High priority

#81 feat: Notas Gerais da matéria e Avaliação de usuários.
  vue-app/src/components/Materias/InfoMateriaComponent.vue
  vue-app/src/components/Professores/InfoProfessorComponent.vue
Labels: feature

#87 fix: arrumado a possibilidade de enviar varias avaliações da mesma materia/professor
  node-app/controllers/AvaliacaoMET.js
  vue-app/src/components/Avaliacao/CardMinhaAvaliacao.vue
  vue-app/src/components/Avaliacao/CardMinhaAvaliacaoProfessor.vue
  vue-app/src/components/Materias/InfoMateriaComponent.vue
  vue-app/src/components/Materias/PopupAvaliaMaterias.vue
  vue-app/src/components/Professores/PopupAvaliaProfessor.vue
  vue-app/src/pages/AvaliacaoPage.vue
  vue-app/src/pages/PerfilPage.vue
  vue-app/src/service/avaliacao/deletarAvaliacao.js
  vue-app/src/service/usuario/editarDadosPerfil.js
  vue-app/src/service/usuario/getMInhasAvaliacoes.js
Labels: API Integration, fix, High priority

#100 Create LICENSE
  LICENSE
Labels: documentation

#104 fix: valida email e url na edição de usuário
  vue-app/jsconfig.json
  vue-app/src/components/Usuario/PopUpEdicaoPerfil.vue
  vue-app/src/generals/verificarInputs.js
Labels: bug, fix, High priority, Security

#108 Adicionado as telas de loading em cada pagina/componente
  vue-app/src/components/Navegacao/LoadingComponent.vue
  vue-app/src/components/Usuario/PopUpEdicaoPerfil.vue
  vue-app/src/pages/AvaliacaoPage.vue
  vue-app/src/pages/HomePage.vue
  vue-app/src/pages/LandingPage.vue
  vue-app/src/pages/LoginPage.vue
  vue-app/src/pages/MateriasPage.vue
  vue-app/src/pages/PerfilPage.vue
  vue-app/src/pages/ProfessorPage.vue
Labels: feature, Low priority, Backlog

#109 fix: realiza verificação de campos de cadastro e login
  node-app/controllers/UserMET.js
  vue-app/src/generals/verificarInputs.js
  vue-app/src/pages/CadastroPage.vue
Labels: bug, fix, High priority
