Repository unb-mds/2024-1-squad04, pull requests merged in 2024-07, with the labels that each got.

#112 feat: adiciona scraping de professores e materias
  banco/criacao/criaBanco.sql
  banco/preenchimento/preencheInformacoesPessoais.py
  banco/preenchimento/preencher.py
  data/dados.json
  data/data.txt
  data/info-pessoais-professores.json
  data/url-fotos.json
  scraping/scraping.txt
  scraping/script-professores.py
  scraping/script-url-fotos.py
Labels: API Integration, High priority

#117 Ajustando a pagina de professor individual
  vue-app/src/components/Navegacao/NavBar.vue
  vue-app/src/components/Professores/InfoProfessorComponent.vue
  vue-app/src/pages/MateriaIndividualPage.vue
  vue-app/src/pages/ProfessorIndividualPage.vue
Labels: fix, Medium priority, Refactor

#118 feat: implementado o filtro de palavrão
  node-app/package-lock.json
  node-app/package.json
  vue-app/package-lock.json
  vue-app/package.json
  vue-app/src/components/Materias/PopupAvaliaMaterias.vue
  vue-app/src/components/Professores/PopupAvaliaProfessor.vue
  vue-app/src/components/Usuario/PopUpEdicaoPerfil.vue
  vue-app/src/generals/verificarPalavrao.js
  vue-app/src/pages/CadastroPage.vue
  vue-app/src/pages/PerfilPage.vue
Labels: Improvement, Medium priority

#119 96 tela login e cadastro ajuste de front end
  vue-app/src/pages/CadastroPage.vue
  vue-app/src/pages/LoginPage.vue
Labels: Improvement, Medium priority

#120 build: define variaveis de ambiente
  node-app/.gitignore
  node-app/index.js
  vue-app/.gitignore
  vue-app/src/components/Avaliacao/AvaliacaoMateriaComponent.vue
  vue-app/src/components/Materias/PopupAvaliaMaterias.vue
  vue-app/src/components/Professores/PopupAvaliaProfessor.vue
  vue-app/src/generals/descriptografarDados.js
  vue-app/src/generals/encripitarDados.js
  vue-app/src/generals/getUsuarioLogado.js
  vue-app/src/repositories/avaliacao/deletarAvaliacoes.js
  vue-app/src/repositories/comentario/deletarLikeDislikeMateria.js
  vue-app/src/repositories/comentario/deletarLikeDislikeProfessor.js
  vue-app/src/repositories/comentario/editarRelacionamentoUsuarioComentario.js
  vue-app/src/repositories/comentario/enviarLikeDislikeMateria.js
  vue-app/src/repositories/comentario/enviarLikeDislikeProfessor.js
  vue-app/src/repositories/materias/enviarAvaliacaoMateria.js
  vue-app/src/repositories/materias/obterMaterias.js
  vue-app/src/repositories/professor/enviarAvaliacaoProfessor.js
  vue-app/src/repositories/professor/obterProfessor.js
  vue-app/src/repositories/usuario/cadastrarUsuario.js
  vue-app/src/repositories/usuario/obterAvaliacoesUsuario.js
  vue-app/src/repositories/usuario/obterInformacoesPerfilUsuario.js
  vue-app/src/repositories/usuario/obterUsuarios.js
  vue-app/src/routes/index.js
  vue-app/src/service/avaliacao/deletarAvaliacao.js
  vue-app/src/service/usuario/editarDadosPerfil.js
  vue-app/src/service/usuario/getMInhasAvaliacoes.js
Labels: Refactor, Build, Security

#123 122 tests testes ponta a ponta da aplicação
  vue-app/cypress.config.js
  vue-app/cypress/e2e/integration/EditUser.cy.js
  vue-app/cypress/e2e/integration/Login-copy-1.cy.js
  vue-app/cypress/e2e/integration/Login.cy.js
  vue-app/cypress/e2e/integration/RatingMateria.cy.js
  vue-app/cypress/e2e/integration/RatingProfessor.cy.js
  vue-app/cypress/fixtures/example.json
  vue-app/cypress/support/commands.js
  vue-app/cypress/support/e2e.js
  vue-app/package-lock.json
  vue-app/package.json
Labels: documentation, Test

#127 fix: corrigido avisos do sonar nos arquivos nodeapp e do scrapping
  docker-compose.yml
  node-app/Dockerfile
  node-app/controllers/AvaliacaoMET.js
  node-app/controllers/ComentarioMET.js
  node-app/controllers/MateriaMET.js
  node-app/controllers/ProfessorMET.js
  node-app/controllers/UserMET.js
  node-app/index.js
  scraping/script-professores.py
  vue-app/src/components/Avaliacao/AvaliacaoMateriaComponent.vue
Labels: Medium priority, Refactor
